lizmap.py

The default mode of the configuration 'source' in the panel 'layers' in the part about 'popup' is now 'auto' instead of 'lizmap'.

Change of default mode of popup source to 'auto'

---

lizmap.py
ui_lizmap.ui

allow user to select thunderforest OpenCycleMap as a map and record the API key
cf #109 
cf https://github.com/3liz/lizmap-web-client/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+440
data exploited in the lizmap web client : https://github.com/3liz/lizmap-web-client/pull/934
tested in QGIS 2.18.21

[FEATURE] add opencyclemap option in the maps

---

lizmap.py

I'm using the QGIS API to add a generated link on my layers, but then I need this PR to have the button in LizMap.
Note: this PR is for QGIS 2. If accepted, I can forwardport to QGIS 3, using both the metadata panel and the qgis server panel.

[FEATURE] auto add the link from metadataUrl in QGIS

---

lizmap.py

for example note the "style" parameter in this URL
contextualWMSLegend=0&crs=EPSG:2056&dpiMode=7&featureCount=10&format=image/png&layers=topo&styles&url=https://sitn.ne.ch/mapproxy95/service

support wms urls thet have parameters with no =

---

ui_lizmap.ui

TAB order sequence is wrong in the QGIS 2 version.
I made the fix in QGIS 3 version because I'm not sure you will release a new version for QGIS 2.

review TAB order in QtDesigner

---

lizmap.py
test/test_ui.py

fix #166 
Disable loading lizmap if the project is stored in QGZ, geopackage or postgis.

check QGZ files when we open lizmap

---

lizmap.py

If a field as an alias lizmap stored the alias instead of the field name. The commit fix it.
It is a critical bug. Can you review and publish a new version ?

[Bugfix] With QgsFieldComboBox use currentField instead of currentText

---

lizmap.py
lizmap_api/config.py

This will create in the CFG file a new section like:
```
"metadata": {
"lizmap_plugin_version": 30107,
"qgis_desktop_version": 30414,
"date_modified": "2020-01-14 14:08:00"
},
```
@mdouchin @rldhont and I started talking about versioning CFG file. It's not clear what we should do next, but at least, LWC can have some information about incompatible CFG file. For instance if the CFG file is too recent compare to LWC.
The QGIS desktop version is redundant with the QGS file.
@nboisteault FYI
I think it doesn't hurt to add this kind of information, for tracking anyway.
Any idea?

add some metadata in CFG file about versions

---

lizmap/definitions/base.py
lizmap/definitions/dataviz.py
lizmap/forms/base_edition_dialog.py
lizmap/forms/dataviz_edition.py
lizmap/forms/table_manager.py
lizmap/forms/trace_dataviz_edition.py
lizmap/resources/ui/ui_form_dataviz.ui
lizmap/resources/ui/ui_trace.ui
lizmap/test/test_dialog_edition.py
lizmap/test/test_table_manager.py
lizmap/test/test_trace_dialog.py

* **Funded by**: Communauté d'agglomération du Grand Narbonne https://www.legrandnarbonne.com/
* **Ticket**: #238 
* **Description**: Support for multi traces in dataviz
For some graphs, we want to be able to add from 1 to N traces on the same graph.
Y, Y2, Z and colors are now hidden from the main table. It's a JSON representation. It's less user-friendly in the table. But I don't have a lot of choices because we can have 1-n traces for a single chart.
In the form, there is now a table to add/remove a trace:

support for multi traces in dataviz

---

lizmap/definitions/edition.py
lizmap/forms/edition_edition.py
lizmap/forms/table_manager.py
lizmap/resources/ui/ui_form_edition.ui
lizmap/test/test_table_manager.py

* Ticket https://github.com/3liz/lizmap-web-client/issues/1665
* Add a checkbox to allow geometry less features
The blue color for people using LWC 3.1, 3.2 will come only when will release dev branch LWC 3.4.

Edition - Add a checkbox to allow geometry less features

---

lizmap/plugin.py

Fix #299 
It seems SIP is confused. In some cases, 
* a group in the legend is **not** a QgsLayerTreeGroup but a QgsLayerTreeNode
* a layer in the legend is **not** a QgsLayerTreeLayer but a QgsLayerTreeNode
https://qgis.org/api/classQgsLayerTreeNode.html is a base class.
@dmarteau @rldhont Did you get similar issue ?

Force cast a Python SIP object in the legend

---

lizmap/server/lizmap_accesscontrol.py

Disbale the lizmap layer filter expression acces control while fixing QGIS Server.
We are facing an issue due to a filter expressions cache in QgsAccessControl.
mFilterFeaturesExpressions in QgsAccessControl is never cleared and it is set only by WMS Request in QgsRenderer::layersRendering with
mContext.accessControl()->resolveFilterFeatures( mapSettings.layers() );

Fix: Disable lizmap layer filter expression access control

---

lizmap/definitions/attribute_table.py
lizmap/definitions/edition.py
lizmap/forms/attribute_table_edition.py
lizmap/forms/base_edition_dialog.py
lizmap/forms/edition_edition.py
lizmap/resources/ui/ui_form_attribute_table.ui
lizmap/test/test_table_manager.py

* **Funded by**: Altétia
* Ticket fix #317  
Hum, so it seems I think i have a weird behavior.
In QGIS Desktop, it seems **always** not empty : 
```python
[ col.name for col in iface.activeLayer().attributeTableConfig().columns()]
```
While in the QGS file : 
```xml
<attributetableconfig actionWidgetStyle="dropDown" sortExpression="" sortOrder="0">
<columns></columns>
</attributetableconfig>
```
https://www.qgis.org/api/classQgsAttributeTableConfig.html#a1af932ad500b11eebc2d88fe6308ed84

CFG - Add a new key if the attribute table has a custom config

---

lizmap/forms/base_edition_dialog.py
lizmap/forms/dataviz_edition.py
lizmap/forms/table_manager.py
lizmap/lizmap_api/config.py
lizmap/plugin.py
lizmap/qt_style_sheets.py
lizmap/resources/ui/ui_lizmap.ui
lizmap/server/get_feature_info.py
lizmap/server/lizmap_server.py
lizmap/test/test_server_core.py
test/server/data/get_feature_info.qgs
test/server/data/get_feature_info.qgs.cfg
test/server/requirements.txt
test/server/run-tests.sh
test/server/test_get_feature_info.py

* **Funded by**: French Province Pyrénées-Atlantiques https://www.le64.fr/
* Get the GetFeatureInfo from QGIS Server with the QGIS Form
@rldhont Should we use our own service/api ?
Or do you want to plug on the GetFeatureInfo request ?
I started on the GetFeatureInfo request as we can see on this draft.
But what would the best workflow ? 
1. Get the result from QGIS Server
2. Parse the result (HTML, GML etc) to have vector layer name and fature ID
3. Make again the QGIS project (to have relations). It seems in a QgsFilter, I couldn't have the Project used.
4. Call the class `Maptip` from Lizmap plugin with QgsVectorLayer and QgsProject
This doesn't seem efficient at all and very fragile so I would like to have your inputs.
At least, by writing the test file provided, I …

Get feature info

---

lizmap/tooltip.py

* **Funded by**: Conseil Départemental des Pyrénées Atlantiques
* **Description**:  The visibility expression was apply on main containers (level 1) and never on inside containers (level greater than 1).

Fix: The visibility is not applied on container with level upper than 1

---

lizmap/plugin.py

* **Ticket**: #352 
* removed ``A Lizmap window is already opened`` warning
* fixed to show dialog in front of QGIS when already opened

#352: show dialog in front of QGIS

---

lizmap/tooltip.py

Instead of displaying the field name in the link for external resource not as web or image, use base_file_name to display the file name in the link of tooltip.

Tooltip: use base_file_name for external resource

---

CHANGELOG.md
lizmap/plugin.py

* **Description**: Remove the check for relative path
* Fix #346 
I think we agreed to totally remove the check for paths.
Users might have data in `/mnt/data` and their project in `/home/etienne/dev/lizmap/test`
`QGIS_SERVER_IGNORE_BAD_LAYERS` or LayerBoard plugin should warn them about these paths.

UX - Remove the check for relative path

---

lizmap/server/lizmap_filter.py

On request ready lizmap plugin set 2 variables with values provided in request:
* lizmap_user
* lizmap_user_groups
These varaibles could be used in Expression service for default values, in WMS GetPrint request or other request that can have  QGIS expressions.

[Server] Set project custom variables to get User login and groups

---

CHANGELOG.md
lizmap/test/test_tooltip.py
lizmap/tooltip.py

In ValueRelation context `@current_geometry` and `current_value('field_name')` can be used to get geometry or values associated to the form. In the tooltip with aggregate function they are not available and has to be replaced by `geometry(@parent)` and `attribute(@parent, '' )`.
* **Funded by**: DDTM34

Tooltip: adapt ValueRelation filter to aggregate context

---

lizmap/plugin.py

After change IGN urls with its new urls of its new services the free key like `ChoisirGeoportail` was deleted. So in the Lizmap plugin  we need to change the behavior of the ignkey with the checkbox to add ign basemaps in the config.
Now we only need an IGN key to use the `scan25` basemap.

Change the behavior of the key compared to the new service ign

---

lizmap/definitions/warnings.py
lizmap/plugin.py

* LWC 3.6 - Check for the layer id as name
New section in the CFG, empty of course if everything is fine : 
```json
"warnings": [
"use_layer_id_as_name",
"ogc_not_valid"
],
```

LWC 3.6 - Check for the layer id as name

---

CHANGELOG.md
lizmap/definitions/definitions.py
lizmap/plugin.py
lizmap/test/data/lizmap_3_3.qgs.cfg
lizmap/version_checker.py

Hop @mdouchin !
So later, you can know if it's a true 3.6 CFG file or a 3.6 ghost with missing keys ...
```json
"metadata": {
"qgis_desktop_version": 31615,
"lizmap_plugin_version": "3.7.8-pre",
"lizmap_web_client_target_version": 30300,
"lizmap_web_client_target_status": "NotMaintained",
"project_valid": false
},
```

CFG - Add the status of the current LWC release in the metadata

---

CHANGELOG.md
lizmap/definitions/definitions.py
lizmap/definitions/filter_by_form.py
lizmap/forms/base_edition_dialog.py
lizmap/forms/filter_by_form_edition.py
lizmap/forms/table_manager.py
lizmap/resources/ui/ui_form_filter_by_form.ui
lizmap/test/test_table_manager.py

* Form filter - allow two numeric filters : start and end values
* Linked to https://github.com/3liz/lizmap-web-client/pull/3162
* Funded by Terre de Provence Agglomération https://www.terredeprovence-agglo.com/
⚠ This PR mustn't be merged before 3.6.0 is released ! It's technically not possible for now to have two dev versions (3.6 and 3.7)

Form filter - allow two numeric filters : start and end values

---

lizmap/server_ftp.py

This has been raided when loading plugin on QGIS built from MinGW GH Action in PR.
```python
mpossible de charger l'extension 'lizmap' provoque une erreur lors de l'appel à sa méthode classFactory() 
AttributeError: 'QLineEdit' object has no attribute 'ssetEnabled' 
Traceback (most recent call last):
File "D:\Downloads\QGIS-Portable\lib\python3.11\site-packages\qgis\utils.py", line 423, in _startPlugin
plugins[packageName] = package.classFactory(iface)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users/godet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\__init__.py", line 58, in classFactory
return Lizmap(iface)
^^^^^^^^^^^^^
File "C:\Users/godet/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 640, in __init__
self.server_ftp = …
```

Fix typo in FTP server

---

lizmap/test/test_tooltip.py
lizmap/tooltip.py

* QGIS concatenate aggregation expression is not working with numeric fields, therefore with need to force a string conversion when creating the tooltip
ref https://github.com/3liz/lizmap-plugin/issues/501 
Probably the same fix should also be done in the lizmap server plugin?

Fix concatenate with number in aggregate

---

lizmap/dialogs/main.py
lizmap/plugin.py

Better UX like this @nboisteault ! It makes it much clearer what to expect.
Note that the state of the checkbox is not lost, just disabled. So we don't loose configuration layer per layer.
Side note, if we enable the maptheme on startup, in a better world, the content of the dropdown menu should be updated : 
It should be either : 
* Follow maptheme
* Disabled
Right ?

UX - Disable the toggled checkbox if the maptheme is enabled

---

lizmap/plugin.py
lizmap/project_checker_tools.py

The best would be to change how the dictionary in the CFG is written, but in the meantime, it's better to **stop** the process (not only warning).
Related to https://github.com/3liz/lizmap-plugin/issues/291, https://github.com/3liz/lizmap-plugin/issues/325

CFG - Error if duplicated layer/group names

---

lizmap/plugin.py

Other groups are already lower case : `hidden`, `baselayers`, `project-background-color`
It would be nice to have `overview` as well to make things easier, same behavior everywhere.
But it seems this is hardcoded in LWC `Overview` : https://github.com/3liz/lizmap-web-client/blob/bc59e16cf30d44c259e70ba152d91a6cae290b30/assets/src/components/OverviewMap.js#L18

Switch from "Overview" to "overview" for the group name

---

lizmap/definitions/atlas.py
lizmap/definitions/attribute_table.py
lizmap/definitions/base.py
lizmap/definitions/filter_by_polygon.py
lizmap/forms/atlas_edition.py
lizmap/forms/attribute_table_edition.py
lizmap/forms/base_edition_dialog.py
lizmap/forms/filter_by_polygon.py
lizmap/resources/ui/ui_form_attribute_table.ui
lizmap/table_manager/base.py

The primary key is asked in 3 tools : 
* atlas
* attribute table
* filter by polygon
Now, if the layer is database based (PG, SQLite or Geopackage), the datasource about the primary key will be set automatically in the CFG file.
The primary key widget will be enabled for other kind of layer.

Do not enable the field combobox when expecting a primary key if the layer is in DB

---

lizmap/definitions/definitions.py
lizmap/plugin.py
lizmap/resources/ui/ui_lizmap.ui

* Recycling the deprecated button stamen to the French orthophoto
* Visible only for developers or French QGIS user
* #471 and https://github.com/3liz/lizmap-web-client/issues/3591

Add buttons for the French orthophoto and plan

---

lizmap/dialogs/dock_html_preview.py
lizmap/plugin.py
lizmap/resources/html/maptip_preview.html
lizmap/resources/ui/ui_lizmap.ui

* Quite slow to use the native HTML maptip in QGIS over the map
* The native display in QGIS is narrow and truncated vertically
* Even with the new feature in QGIS 3.32 https://changelog.qgis.org/en/qgis/version/3.32/#map-tip-preview
* This viewer has the Lizmap bootstrap CSS included

UX - Add a new dock for HTML maptip preview

---

lizmap/definitions/definitions.py
lizmap/dialogs/main.py
lizmap/plugin.py
lizmap/resources/ui/ui_lizmap.ui
lizmap/test/test_ui.py

Only when we click on a "direct" children of `baselayers` we can access these widgets.
The server tile cache is only enabled when single tile is OFF (not shown in the GIF above)
CC @rldhont @mind84 and @nboisteault  Does it work for you ?

UX - Enable more widgets when clicking in the baselayers predefined group

---

lizmap/plugin.py
lizmap/widgets/check_project.py

Until the regression is identified, it's better to warn users having inverted axis
Linked to https://github.com/3liz/lizmap-web-client/issues/4191
When the bug is fixed, this check will be removed
CC @aeduard

Check for inverted axis in project CRS

---

lizmap/plugin.py
lizmap/test/test_postgresql.py
lizmap/test/test_ui.py

Because we don't know the layer tree in the CFG about where is `default-background-color`,  to make the life easier
```json
"options": {"default_background_color" : True}
```

CFG - Add new key for default-background-color

---

lizmap/plugin.py

Fix #601
It has been tested successfully by @mind84
@rldhont @mdouchin Any drawbacks ?

Enable again the embedded text input widget if the layer is in "baselayers"

---

lizmap/plugin.py
lizmap/test/test_tooltip.py
lizmap/tooltip.py

Update tooltip template to include classes and proper html elements for Bootstrap 5 compatibility (see https://github.com/3liz/qgis-lizmap-server-plugin/pull/87)

update html tooltip to handle bootstrap 5 tabs

---

lizmap/tooltip.py

If text widget is configured as a root children then it is stored in the `content_tabs` list instead of in `before_tabs` or `after_tabs` lists. On client side, if tabs are configured, then users see the text widget in all tabs as consequence.

Place text widget in right list

---

lizmap/dialogs/main.py
lizmap/lizmap_api/config.py
lizmap/plugin.py
lizmap/resources/ui/ui_lizmap.ui
lizmap/test/test_ui.py

* **Funded by**: [CC Bièvre Est](https://www.bievre-est.fr/)
* Two new scales when zooming : max scale for points or other geom
If the value in the widget is the same as the default, it's not written in the CFG file, to avoid not needed keys.
@nboisteault What do you think 5000.0 ?

Two new scales when zooming : max scale for points or other geom

---

lizmap/definitions/definitions.py
lizmap/dialogs/main.py
lizmap/dialogs/news.py
lizmap/dialogs/scroll_message_box.py
lizmap/dialogs/server_wizard.py
lizmap/dialogs/wizard_group.py
lizmap/drag_drop_dataviz_manager.py
lizmap/forms/base_edition_dialog.py
lizmap/forms/dataviz_edition.py
lizmap/forms/layout_edition.py
lizmap/plugin.py
lizmap/plugin_manager.py
lizmap/server_dav.py
lizmap/server_lwc.py
lizmap/table_manager/base.py
lizmap/table_manager/dataviz.py
lizmap/table_manager/layouts.py
lizmap/test/test_ui.py
lizmap/test/test_wizard.py
lizmap/toolbelt/debug.py
lizmap/toolbelt/plugin.py
lizmap/widgets/check_project.py
lizmap/widgets/list_fields_selection.py
lizmap/widgets/list_layers_selection.py
lizmap/widgets/selectable_combobox.py
lizmap/widgets/table_files.py

Hopefully, it will fix #616 
@nicogodet Can you try this fix ?
It was a hard search and replace from `Qt.UserRole` to `Qt.ItemDataRole.UserRole`
If so, I will edit the wiki https://github.com/qgis/QGIS/wiki/Plugin-migration-to-be-compatible-with-Qt5-and-Qt6 and raise the issue about the migrating script.
Thanks for your early testing.

Qt6 - Change Qt.UserRole to Qt.ItemDataRole.UserRole

---

lizmap/definitions/lizmap_cloud.py
lizmap/plugin.py
lizmap/project_checker_tools.py
lizmap/server_lwc.py
lizmap/test/test_version_info.py
lizmap/widgets/check_project.py

@rldhont OK for you ?
CF Paid support 3280

Tip - Trailing spaces can be added

---

lizmap/definitions/attribute_table.py
lizmap/forms/attribute_table_edition.py
lizmap/forms/base_edition_dialog.py
lizmap/resources/ui/ui_form_attribute_table.ui
lizmap/test/test_table_manager.py

* Allow groups ACL for layer export capabilities
CC @mind84

feat: Allow groups ACL for layer export capabilities
