- lizmap.py
- ui_lizmap_popup.py
- ui_lizmap_popup.ui
> [enhancement] use QgsCodeEditorHTML to configure layer popup

- lizmap.py
> [BUGFIX] Tools layer limit linked to combobox size

- lizmap.py
fix https://github.com/3liz/lizmap-plugin/issues/68
> "hide checkboxes for groups" always checked

- i18n/lizmap_en.ts
- lizmap.py
- ui_lizmap.ui
Add the ability to the map builder to configure the amount of features per layer displayed in popup.
Linked to:
* https://github.com/3liz/lizmap-web-client/pull/489
* https://github.com/3liz/lizmap-web-client/issues/630
* https://github.com/3liz/lizmap-web-client/issues/430
> [FEATURE] Configure the amount of features per layer displayed in popup

- lizmap.py
fix API break from QGIS 2 to 3 about QgsMessagebar
> fix API break from QGIS 2 to 3 about QgsMessagebar

- lizmapdialog.py
- lizmappopupdialog.py
Fix Qt5 import and remove Qt4 supports (which is uselees with QGis 3)
> Fix Qt5 imports

- lizmap.py
- ui_lizmap.ui
The feature permit you to hide the parent plot if you only want the see the children
> [Enhancement] Creation of a checkbox in Dataviz used to hide the parent plot 

- .gitignore
- lizmap.py
- metadata.txt
* Fix icon
* Pycharm is warning me about these unused imports
> fix icons in plugin manager, remove unused imports

- lizmap.py
Issue: https://github.com/3liz/lizmap-web-client/issues/902
* Fixing missing imports when opening the help
* Add more languages at the same time ;-)
* Add a warning when a layer has some Z or M values
I can backport to master.
> Add warning about Z or M values

- README.md
- lizmap.py
For the warning about ZM values, it's not straightforward in QGIS 2 because there isn't such a function in QGIS  2 to know if a geometry has Z or M (I had a quick look only)
> Backport on the qgis2 branch

- ui_lizmap_popup.py
Fix to : 
https://github.com/3liz/lizmap-plugin/issues/111
> Enable popup configuration of a project layer (Layers panel)

- __init__.py
- lizmap.py
I let PyCharm fixes these PEP8 automatically. I got a lot of warnings before.
I hope it's fine.
> automatic fix from PyCharm about PEP8

- lizmap.py
remove unused code about clock fix #148
> remove unused code about clock fix #148

- lizmap.py
> disable configure button if popup is not lizmap mode

- lizmap.py
- lizmap_api/config.py
- resources/ui/ui_lizmap.ui
* Disable popup panel if the checkbox is disabled
* Disable server cache panel if the checkbox is disabled
* Disable server cache if use single tile is used fix #160
> add UI groups for popup and server cache, also fix #160

- lizmap.py
Some legacy?
I just noticed these lines while reviewing #179 from @rldhont
> remove unused code

- lizmap.py
Ths fix the way tooltip is build from QGIS Drag and Drop form.
> [Bugfix] In build tooltip from Drag and Drop form, outside fields are not outside tabs

- resources/ui/ui_lizmap.ui
I will merge as soon as Travis is happy
> more tooltips in the UI

- lizmap.py
- lizmap_api/config.py
- resources/ui/ui_lizmap.ui
revert end attribute which is LWC 3.4 feature 29c52b538bce709cb33b226a7e80249fc45aa0c7
Sorry @mdouchin I would like to release a bug fix version.
3.4 is still on development.
> revert end attribute which is LWC 3.4 feature #29c52b5

- .travis.yml
- test/test_code_layout.py
- test/test_ui.py
QGIS 3.10 is now the current LTR.
I will remove 3.4 when we will decide to not support 3.4 versions.
> enable QGIS 3.10 on travis

- definitions/__init__.py
- definitions/atlas.py
- definitions/base.py
- forms/__init__.py
- forms/atlas_edition.py
- forms/base_edition_dialog.py
- forms/table_manager.py
- lizmap.py
- lizmap_api/config.py
- resources/ui/ui_form_atlas.ui
- resources/ui/ui_lizmap.ui
- test/test_dialog_edition.py
- test/test_table_manager.py
Add Multiatlas fix #141
Compare to previous PR, this will allow us to hide some fields in the form itself (like data filtering by field, or in the dataviz panel). This is going to be better for UX.
* Add new row
* Remove existing row
* Edit an existing row ! Fix #139 
* Reorder rows Fix #151
* These tables won't listen any events if there isn't a CFG file #154  
Not ready for review
> Multiatlas and form edition

- definitions/locate_by_layer.py
- forms/locate_layer_edition.py
- forms/table_manager.py
- lizmap.py
- resources/ui/ui_form_locate_layer.ui
- resources/ui/ui_lizmap.ui
- test/data/lizmap_3_3.qgs
- test/data/lizmap_3_3.qgs.cfg
- test/test_table_manager.py
Port the locate by layer tool to the new form generation
Next panels should be easier because locate by layer is the first panel ported.
> moving locate by layer to the new form

- definitions/filter_by_login.py
- forms/atlas_edition.py
- forms/base_edition_dialog.py
- forms/filter_by_login.py
- forms/locate_layer_edition.py
- forms/table_manager.py
- lizmap.py
- resources/ui/ui_form_filter_by_login.ui
- resources/ui/ui_lizmap.ui
- test/data/lizmap_3_3.qgs
- test/data/lizmap_3_3.qgs.cfg
- test/test_table_manager.py
Porting filter by login panel to the new form
> make the filter by login editable

- definitions/attribute_table.py
- definitions/base.py
- definitions/tooltip.py
- forms/attribute_table_edition.py
- forms/base_edition_dialog.py
- forms/table_manager.py
- forms/tooltip_edition.py
- lizmap.py
- resources/ui/ui_form_attribute_table.ui
- resources/ui/ui_form_tooltip.ui
- resources/ui/ui_lizmap.ui
- test/data/lizmap_3_3.qgs.cfg
- test/test_dialog_edition.py
- test/test_table_manager.py
Port the tooltip panel and attribute table
> port the tooltip and attribute table panels

- definitions/base.py
- definitions/edition.py
- forms/base_edition_dialog.py
- forms/edition_edition.py
- forms/table_manager.py
- lizmap.py
- resources/ui/ui_form_edition.ui
- resources/ui/ui_lizmap.ui
- test/test_table_manager.py
port edition panel to be editable
> port edition panel to be editable

- .gitignore
- definitions/base.py
- definitions/time_manager.py
- forms/base_edition_dialog.py
- forms/table_manager.py
- forms/time_manager_edition.py
- lizmap.py
- resources/ui/ui_form_time_manager.ui
- resources/ui/ui_lizmap.ui
- test/test_table_manager.py
> port time manager to the editable form

- definitions/filter_by_form.py
- forms/filter_by_form_edition.py
- forms/table_manager.py
- lizmap.py
- resources/ui/ui_form_filter_by_form.ui
- resources/ui/ui_lizmap.ui
- test/test_table_manager.py
Port the form filter panel to be editable
> port the form filter to be editable

- __init__.py
- definitions/definitions.py
- html_and_expressions.py
- lizmap.py
- lizmap_api/config.py
- resources/ui/ui_lizmap.ui
Version 3.1, 3.2, 3.3, 3.4
Lizmap 3.4 is coming soon. I don't want to loose 3.2 configuration.
With this flag, I will be able to start breaking the CFG file for Lizmap 4.
This is stored in the QGIS profile (not per project).
> add version LWC version selector

- definitions/time_manager.py
- forms/time_manager_edition.py
- resources/ui/ui_form_time_manager.ui
- test/test_table_manager.py
@mdouchin I merged the new time manager from `master` to `dev` and obviously I got some conflicts. I just accepted the `master` branch. So it means the `dev` is back to previous https://github.com/3liz/lizmap-plugin/commit/e4c1c27c93d7bbcbcb2bbed14ec9c5b296524d3e
This commit is a port of your commit https://github.com/3liz/lizmap-plugin/commit/e4c1c27c93d7bbcbcb2bbed14ec9c5b296524d3e in the new system. I will let you review and we can check later.
> follow up e4c1c27 about time manager in 3.4

- .travis.yml
> enable travis on QGIS Server tests

- lizmap/__init__.py
- lizmap/metadata.txt
- lizmap/server/core.py
- lizmap/server/expression_service.py
- lizmap/server/lizmap_filter.py
- lizmap/server/lizmap_server.py
- lizmap/server/lizmap_service.py
- test/server/test_expression_service.py
- test/server/test_expression_service_evaluate.py
- test/server/test_expression_service_getfeaturewithformscope.py
- test/server/test_expression_service_replaceexpressiontext.py
- test/server/test_expression_service_virtualfields.py
- test/server/test_lizmap_service.py
First tool is checking project lizmap acl configuration
> [Server] Start implementing lizmap server side

- lizmap/test/test_tooltip.py
- lizmap/tooltip.py
> escape characters in tooltips

- lizmap/definitions/dataviz.py
- lizmap/forms/dataviz_edition.py
- lizmap/resources/ui/ui_form_dataviz.ui
- lizmap/test/test_table_manager.py
> Dataviz - New option: display when layer visible

- lizmap/definitions/base.py
- lizmap/definitions/edition.py
- lizmap/forms/base_edition_dialog.py
- lizmap/forms/edition_edition.py
- lizmap/forms/table_manager.py
- lizmap/resources/ui/ui_form_edition.ui
- lizmap/test/test_table_manager.py
Funded by French province "Département des Pyrénées-Atlantiques"
http://www.le64.fr/accueil.html
```
"editionLayers": {
"cat_points": {
"layerId": "cat_points20180404162506881",
"acl": "admins",
"snap_layers": "layer_id_1,layer_id_2",
"snap_node": "True",
"snap_segments": "True",
"snap_intersections": "False",
"capabilities": {
"createFeature": "True",
"modifyAttribute": "True",
"modifyGeometry": "True",
"deleteFeature": "True"
},
"geometryType": "point",
"order": 0
}
},
```
> add snapping config in edition panel

- .travis.yml
- lizmap/test/test_dialog_edition.py
- lizmap/test/test_table_manager.py
- lizmap/test/test_tooltip.py
- lizmap/test/test_ui.py
> remove start_app in tests files

- lizmap/lizmap_api/config.py
- lizmap/plugin.py
- lizmap/resources/ui/ui_lizmap.ui
Are we sure it will be only for groups?
> add option for group visibility

- lizmap/definitions/edition.py
- lizmap/forms/edition_edition.py
- lizmap/resources/ui/ui_form_edition.ui
- lizmap/test/test_dialog_edition.py
- lizmap/test/test_table_manager.py
CF https://projects.3liz.org/3liz/management/suivi-developpements/issues/46#note_23328
> rename nodes to vertices

- lizmap/definitions/edition.py
- lizmap/forms/base_edition_dialog.py
- lizmap/forms/edition_edition.py
- lizmap/forms/table_manager.py
- lizmap/resources/ui/ui_form_edition.ui
- lizmap/test/test_table_manager.py
* **Funded by**: French province "Département des Pyrénées-Atlantiques"
http://www.le64.fr/accueil.html
* add tolerance for snapping
CF : https://projects.3liz.org/3liz/management/suivi-developpements/issues/46#note_23374
> add tolerance for snapping

- lizmap/definitions/base.py
- lizmap/definitions/dataviz.py
- lizmap/forms/base_edition_dialog.py
- lizmap/forms/table_manager.py
- lizmap/plugin.py
- lizmap/resources/ui/ui_lizmap.ui
This is mainly for Lizmap 3.4 about the new dataviz panel
> check lizmap version also in panel general config

- lizmap/definitions/base.py
- lizmap/definitions/dataviz.py
- lizmap/forms/base_edition_dialog.py
- lizmap/forms/dataviz_edition.py
- lizmap/forms/table_manager.py
- lizmap/resources/ui/ui_form_dataviz.ui
- lizmap/test/test_table_manager.py
* **Funded by**: Le Grand Narbonne https://www.legrandnarbonne.com/
* add a JSON input widget for dataviz layout
> add a JSON input widget for dataviz layout

- lizmap/definitions/dataviz.py
- lizmap/forms/dataviz_edition.py
- lizmap/forms/table_manager.py
- lizmap/test/test_table_manager.py
* #259 
* No aggregation is required sometimes for the Box chart
> fix Box chart when there is no aggregation

- lizmap/server/lizmap_service.py
- test/server/pytest.ini
- test/server/test_lizmap_service.py
* Following the discusion on IRC last week
I think for security, we need to add a flag about these values, to not be enabled by default
> add gdal version in lizmap server

- lizmap/definitions/filter_by_login.py
- lizmap/forms/filter_by_login.py
- lizmap/resources/ui/ui_form_filter_by_login.ui
- lizmap/test/test_table_manager.py
* **Funded by**: French province Calvados CD 14  https://www.calvados.fr/
* Filter by user on edition only
> filter by user on edition only

- lizmap/server/lizmap_filter.py
* **Funded by**: Conseil Départemental du Vaucluse
* Add some comments to Lizmap QGIS Server Filter
> Add comment to Lizmap QGIS Server Filter

- lizmap/server/lizmap_accesscontrol.py
- lizmap/server/lizmap_server.py
- test/server/conftest.py
- test/server/data/france_parts_liz.qgs
- test/server/data/france_parts_liz.qgs.cfg
- test/server/data/france_parts_liz_grp_v.qgs
- test/server/data/france_parts_liz_grp_v.qgs.cfg
- test/server/test_lizmap_accesscontrol.py
* **Funded by**:  Conseil Départemental du Vaucluse
* **Description**: Create Lizmap QGIS Server Access Control Filter
> Create Lizmap QGIS Server Access Control Filter

- lizmap/server/lizmap_filter.py
- test/server/data/france_parts_liz_acl.qgs
- test/server/data/france_parts_liz_acl.qgs.cfg
- test/server/test_lizmap_filter.py
* **Description**: Finalize the Lizmap Server Filter to control acces based on project Lizmap ACL
> Lizmap Server Filter Groups

- lizmap/definitions/time_manager.py
- lizmap/forms/base_edition_dialog.py
- lizmap/forms/time_manager_edition.py
- lizmap/resources/ui/ui_form_time_manager.ui
- lizmap/test/data/lines.geojson
- lizmap/test/test_dialog_edition.py
- lizmap/test/test_tools.py
- lizmap/tools.py
* **Funded by**: Communauté d'agglomération du Grand Narbonne https://www.legrandnarbonne.com/
* **Ticket** #274 
* New fields in the time manager dialog
> Time manager - add min and max values in the config dialog 

- lizmap/lizmap_api/config.py
- lizmap/plugin.py
- lizmap/resources/ui/ui_lizmap.ui
* **Funded by**: [PNR Ballon des Vosges](https://www.parc-ballons-vosges.fr/).
* Allow to enable or not the drawing tools
```json
"options": {
...
"draw": "True",
...
},
```
CC @nboisteault
> Tools - Add drawing tool checkbox

- lizmap/definitions/definitions.py
- lizmap/lizmap_api/config.py
- lizmap/plugin.py
- lizmap/resources/ui/ui_lizmap.ui
- lizmap/test/test_layer_tree.py
- lizmap/tools.py
* **Funded by**: Bugfix 3liz
* Fix #189 
* add button to get the link from layer properties `dataUrl`
> Metadata - add button to get the link from layer properties

- .travis.yml
Add travis  plugin server tests for Qgis 3.14
> Add travis server tests for Qgis 3.14

- .travis.yml
* **Funded by**: Ourself
* Travis - Review configuration
> Travis - Review configuration

- lizmap/server/core.py
- lizmap/server/lizmap_accesscontrol.py
- lizmap/test/test_server_core.py
- test/server/data/france_parts.qgs
- test/server/data/france_parts_liz.qgs
- test/server/data/france_parts_liz_acl.qgs
- test/server/data/france_parts_liz_filter_group.qgs
- test/server/data/france_parts_liz_filter_group.qgs.cfg
- test/server/data/france_parts_liz_filter_login.qgs
- test/server/data/france_parts_liz_filter_login.qgs.cfg
- test/server/data/france_parts_liz_grp_v.qgs
- test/server/test_lizmap_accesscontrol.py
* Implement `layerFilterExpression` based on `loginFilteredLayers`
* Implement `layerFilterSubsetString` based on `loginFilteredLayers`
> Server Access control layer filter

- setup.cfg
- test/server/test_lizmap_accesscontrol.py
* Try to update the exclude section of setup.cfg
> Update exclude section of setup.cfg

- lizmap/lizmap_api/config.py
- lizmap/plugin.py
- lizmap/server/lizmap_accesscontrol.py
- lizmap/test/data/lizmap_3_3.qgs.cfg
- lizmap/test/test_layer_tree.py
- test/server/data/france_parts_liz_grp_v.qgs.cfg
* Use proper JSON list instead of string
* Ticket #292
> CFG - Make the group_visibility a list in the JSON

- lizmap/forms/time_manager_edition.py
- lizmap/test/test_dialog_edition.py
Fix possible error when computing min and max values from QDateTime
Tests needed @Gustry
> Fix time manager

- lizmap/forms/table_manager.py
- lizmap/test/test_table_manager.py
* **Funded by**:  3Liz.com
* CFG - Set a default value when the value is unknown for a list
> CFG - Set a default value when the value is unknown for a list

- lizmap/server/core.py
- lizmap/server/lizmap_accesscontrol.py
* **Funded by**: Grand Narbonne
* **Description**:  
* Lizmap server plugin does not take into account the Lizmap Web Client override login by filter.
> [Bugfix] Lizmap Web Client override login by filter is not respected

- lizmap/server/lizmap_accesscontrol.py
* Server - Re-enable Lizmap expression filtering on server, follow up #321
If I got it correct @rldhont
> Server - Re-enable Lizmap expression filtering on server, follow up #321

- lizmap/server/lizmap_accesscontrol.py
- lizmap/server/lizmap_filter.py
> [Server] Filter - Check headers content before reading config to improve perf

- lizmap/server/lizmap_accesscontrol.py
* **Funded by**:  3Liz
* Server - some code simplification
> Server - some code simplification

- lizmap/server/filter_by_polygon.py
- lizmap/test/test_filter_by_polygon.py
> Filter - Fix the spatial_relationship not taken into account

- CHANGELOG.md
- lizmap/plugin.py
I'm not a big fan of this kind of warning/message box poping-up, but maybe it will help them ?
* It doesn't block the saving of the CFG file. Only a "ok" is enough.
* We can still enter a wrong URL, there isn't a check on that, "https://idontcare.com" will work to remove the warning
@nboisteault @mdouchin @rldhont Any thoughts ?
> UX - Make the server list recommended

- CHANGELOG.md
- lizmap/forms/edition_edition.py
- lizmap/forms/filter_by_polygon.py
- lizmap/tools.py
Do we agree ?
@rldhont @mdouchin @nboisteault @drillinP 
This is not blocking on the LWC some old CFG unfortunetaly :p You still have some work to do ;-)
Linked to #361
> Provider - Removing Spatialite for editing capabilities

- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- README.md
- lizmap/server/lizmap_server.py
- lizmap/server/server_info_handler.py
- lizmap/server/tools.py
- test/server/test_server_info.py
* Server - Add API to fetch information from QGIS Server
Superseed #335
Need to check with @dmarteau :  
* URL of QGIS. For me it's "http://qgis.server/master/" but then, I need to set `/master/lizmap` in `_ServerApi`, see the commented line
This PR is needed for merging https://github.com/3liz/lizmap-web-client/pull/2654
> Server - Add API to fetch information from QGIS Server

- lizmap/server/server_info_handler.py
@dmarteau That's why tests are passing and it's working with FCGI.
I couldn't try, I don't have Py-QGIS-Server @dmarteau
> In Py-QGIS-Server, plugin_list is a function instead of a list

- lizmap/dialog_server_form.py
- lizmap/resources/ui/ui_form_server.ui
- lizmap/resources/ui/ui_lizmap.ui
- lizmap/server_lwc.py
* UX - Add credentials support when saving Lizmap server URL
Still not used, users can set the login and save the password for a single Lizmap server for now
> UX - Add credentials support when saving Lizmap server URL

- CHANGELOG.md
- lizmap/server/filter_by_polygon.py
- lizmap/test/test_filter_by_polygon.py
Server - Fix the filter by polygon when the field is a string
> Server - Fix the filter by polygon when the field is a string

- CHANGELOG.md
- lizmap/dialog_server_form.py
- lizmap/metadata.txt
- lizmap/plugin.py
- lizmap/server_lwc.py
- lizmap/test/test_tooltip.py
- lizmap/tooltip.py
If nothing against, I will merge later this week for the next release.
> Raise QGIS minimum version to 3.10

- CHANGELOG.md
- lizmap/definitions/attribute_table.py
- lizmap/forms/table_manager.py
Linked to https://github.com/3liz/lizmap-web-client/issues/2780
**Funded by**: 3Liz
CC @nboisteault @rldhont @mdouchin
> CFG - Add default value when saving the CFG file

- lizmap/forms/table_manager.py
> Table manager - fix a minor issue

- CHANGELOG.md
- lizmap/definitions/filter_by_polygon.py
- lizmap/forms/base_edition_dialog.py
- lizmap/forms/filter_by_polygon.py
- lizmap/forms/table_manager.py
- lizmap/resources/ui/ui_form_filter_by_polygon.ui
- lizmap/test/test_table_manager.py
Filtering - Add new option by centroid for filtering by polygon
The check is done when saving the editing form, when saving the CFG as well
https://github.com/3liz/qgis-lizmap-server-plugin/issues/15
> Filtering - Add new option by centroid for filtering by polygon

- CHANGELOG.md
- lizmap/definitions/dataviz.py
- lizmap/forms/dataviz_edition.py
- lizmap/resources/ui/ui_form_dataviz.ui
- lizmap/test/test_table_manager.py
* **Funded by**: [Direction Départementale des Territoires et de la Mer de l'Hérault DDTM 34](https://www.herault.gouv.fr/Services-de-l-Etat/Agriculture-environnement-amenagement-et-logement/Direction-Departementale-des-Territoires-et-de-la-Mer-de-l-Herault-DDTM-34)
> Dataviz - New options for title in popup, not filter data

- lizmap/table_manager/dataviz.py
- lizmap/test/test_tools.py
- lizmap/tools.py
Dataviz - Fix the instance name is duplicated in the URL for plotly
> Dataviz - Fix the instance name is duplicated

- CHANGELOG.md
- lizmap/plugin.py
- lizmap/server_lwc.py
- lizmap/test/data/version_info_27032023.json
- lizmap/test/test_version_info.py
Some previous work I found in a branch, to be continued soon.
> Preliminary work about qgis server check

- CHANGELOG.md
- lizmap/ogc_project_validity.py
- lizmap/plugin.py
- lizmap/test/data/shortnames.qgs
- lizmap/test/test_ogc_project_validity.py
* **Funded by**:  3Liz
* OGC - Check project validity and add shortnames if possible
Can someone review the test file ? Did I miss some layer name ?
CC @nboisteault @rldhont @mdouchin
> OGC - Check project validity and add shortnames if possible

- .github/workflows/ci.yml
- lizmap/definitions/dataviz.py
- lizmap/dialogs/drag_drop_dataviz_container.py
- lizmap/drag_drop_dataviz_manager.py
- lizmap/plugin.py
- lizmap/resources/ui/ui_drag_drop_dataviz.ui
- lizmap/resources/ui/ui_lizmap.ui
- lizmap/table_manager/base.py
- lizmap/test/data/dataviz_drag_drop.qgs
- lizmap/test/data/dataviz_drag_drop.qgs.cfg
- lizmap/test/test_drag_drop_dataviz.py
- lizmap/test/test_table_manager.py
* Add a drag drop for the dataviz layout
* **Funded by**: [Direction Départementale des Territoires et de la Mer de l'Hérault DDTM 34](https://www.herault.gouv.fr/Services-de-l-Etat/Agriculture-environnement-amenagement-et-logement/Direction-Departementale-des-Territoires-et-de-la-Mer-de-l-Herault-DDTM-34)
> Drag&Drop dataviz

- .docker/start.sh
- lizmap/definitions/definitions.py
- lizmap/dialogs/main.py
- lizmap/plugin.py
- lizmap/resources/ui/ui_lizmap.ui
- lizmap/server_dav.py
- lizmap/server_lwc.py
- lizmap/table_manager/dataviz.py
- lizmap/test/test_webdav.py
- requirements/dev.txt
No wizard included.
Only the dav class
> Add a class to manage webdav and add some logic

- lizmap/test/test_tooltip.py
- lizmap/tooltip.py
* support for Text Widget in forms (https://github.com/qgis/QGIS/pull/51323)
> [FEATURE] Text widget in tooltip

- lizmap/dialogs/dock_html_preview.py
- lizmap/resources/html/maptip_preview.html
Add main.css and map.css in the HTML maptip dock preview
> Add main.css and map.css in the HTML maptip dock preview

- lizmap/__init__.py
- lizmap/definitions/definitions.py
- lizmap/dialogs/main.py
- lizmap/forms/atlas_edition.py
- lizmap/forms/attribute_table_edition.py
- lizmap/forms/base_edition_dialog.py
- lizmap/forms/dataviz_edition.py
- lizmap/forms/edition_edition.py
- lizmap/forms/filter_by_form_edition.py
- lizmap/forms/filter_by_login.py
- lizmap/forms/filter_by_polygon.py
- lizmap/forms/layout_edition.py
- lizmap/forms/locate_layer_edition.py
- lizmap/forms/time_manager_edition.py
- lizmap/forms/tooltip_edition.py
- lizmap/lizmap_api/config.py
- lizmap/plugin.py
- lizmap/table_manager/base.py
- lizmap/test/test_definitions.py
- lizmap/test/test_dialog_edition.py
- lizmap/test/test_layer_tree.py
- lizmap/test/test_table_manager.py
- lizmap/test/test_ui.py
- lizmap/version_checker.py
* Review LwcVersions to not have a hardcoded value in the plugin
> Review LwcVersions to nto have a hardcoded value in the plugin

- lizmap/dialogs/main.py
- lizmap/plugin.py
- lizmap/project_checker_tools.py
- lizmap/test/test_table_checks.py
- lizmap/widgets/check_project.py
Allow text to be translated in production
> Translations

- lizmap/project_checker_tools.py
- lizmap/widgets/check_project.py
> Add missing pyramid check on a raster

- lizmap/dialogs/main.py
- lizmap/resources/ui/ui_lizmap.ui
> Let API keys outside of the deprecated panel

- lizmap/definitions/atlas.py
- lizmap/definitions/attribute_table.py
- lizmap/definitions/dataviz.py
- lizmap/definitions/edition.py
- lizmap/definitions/locate_by_layer.py
- lizmap/definitions/time_manager.py
- lizmap/definitions/tooltip.py
- lizmap/dialogs/main.py
- lizmap/forms/base_edition_dialog.py
- lizmap/forms/edition_edition.py
- lizmap/plugin.py
- lizmap/table_manager/base.py
- lizmap/table_manager/dataviz.py
- lizmap/test/test_table_manager.py
- lizmap/widgets/check_project.py
- lizmap/widgets/project_tools.py
Will fix mostly #451
Fix #82
Linked to #389
https://github.com/3liz/lizmap-web-client/issues/3952
> Add new checks about WFS for layers and fields

- lizmap/project_checker_tools.py
- lizmap/test/test_project_checker_tools.py
- lizmap/widgets/check_project.py
Linked to https://github.com/3liz/lizmap-web-client/issues/4207
> Add French GEOPF check

- lizmap/plugin.py
- lizmap/test/test_ui.py
Follow up from #568
0 is at the top of the group.
CC @nboisteault
> Instead of bool give the index of the background color

- lizmap/lizmap_api/config.py
Fix #575
@nboisteault You can adapt if needed.
Mainly linked to https://github.com/3liz/lizmap-web-client/issues/1683
> Add WebP format for the layer settings

- lizmap/dialogs/main.py
- lizmap/lizmap_api/config.py
- lizmap/plugin.py
- lizmap/resources/ui/ui_lizmap.ui
In the main section of the JSON, add a new option to enable the automatic permalink : `automatic_permalink`.
It will be disabled by default.
CC @nboisteault and @rldhont
> New checkbox to disable the automatic permalink

- lizmap/tooltip.py
Linked to https://github.com/3liz/qgis-lizmap-server-plugin/pull/85
> Bulk conversion to fstring format for tooltip.py

- lizmap/definitions/filter_by_login.py
- lizmap/forms/filter_by_login.py
- lizmap/resources/ui/ui_form_filter_by_login.ui
- lizmap/test/test_table_manager.py
Linked to https://github.com/3liz/lizmap-web-client/pull/4559 and https://github.com/3liz/qgis-lizmap-server-plugin/pull/86
I think I will review the strings to be clear.
I don't like checkbox, I used a dropdown menu, for UX.
Funded by: Conseil Départemental du Calvados https://www.calvados.fr/
> New option to allow multiple ACL values withing the same field

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- Makefile
- lizmap/dialogs/dock_html_preview.py
- lizmap/dialogs/main.py
- lizmap/dialogs/server_wizard.py
- lizmap/metadata.txt
- lizmap/plugin.py
- lizmap/server_lwc.py
- lizmap/test/test_dialog_edition.py
- lizmap/test/test_trace_dialog.py
- lizmap/test/test_webdav.py
- lizmap/toolbelt/version.py
- lizmap/widgets/check_project.py
Removing code related to QGIS < 3.22
> Raise QGIS minimum version to 3.22

- lizmap/plugin.py
- lizmap/test/test_tooltip.py
- lizmap/tooltip.py
* If LWC 3.7 or lower : legacy CSS
* If LWC 3.8.0 to LWC 3.8.6 : new CSS from https://github.com/3liz/qgis-lizmap-server-plugin/pull/107
* If LWC >= 3.8.7, no CSS included https://github.com/3liz/lizmap-web-client/pull/5571 and backports to 3.8, 3.9 and master
> Popup - Update the CSS for LWC 3.8.0 to 3.8.6, do not provide CSS if higher than 3.8.7 included

- lizmap/table_manager/base.py
- lizmap/test/test_table_manager.py
> Fix export attribute when set to False, do not restore its default value which is True

- lizmap/test/test_tooltip.py
- lizmap/tooltip.py
Related https://github.com/3liz/lizmap-plugin/issues/241
Related to https://github.com/3liz/qgis-lizmap-server-plugin/pull/110
@mdouchin There are other kind of widgets which should be covered by the represent_value I guess, like the checkbox widget.
> Expressions - use represent_value in some cases

- CHANGELOG.md
- lizmap/plugin.py
"master"
* **Funded by**: Grand Narbonne paid support
* Fix https://support.3liz.com/issues/3585
> Fix: `WMSAddWktGeometry` set to `1` instead of `true`

- .github/workflows/ci.yml
- .github/workflows/transifex.yml
Require qgis-plugin-ci workflows to use house-built image.
> Update qgis-plugin-ci workflows
